// source: protos/agent.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.protos.SubsrcribeResponse');
goog.provide('proto.protos.SubsrcribeResponse.EventResponse');
goog.provide('proto.protos.SubsrcribeResponse.MessageDataCase');
goog.provide('proto.protos.SubsrcribeResponse.MessageType');
goog.provide('proto.protos.SubsrcribeResponse.UploadResponse');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.protos.SubsrcribeResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.protos.SubsrcribeResponse.oneofGroups_);
};
goog.inherits(proto.protos.SubsrcribeResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.protos.SubsrcribeResponse.displayName = 'proto.protos.SubsrcribeResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.protos.SubsrcribeResponse.EventResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.protos.SubsrcribeResponse.EventResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.protos.SubsrcribeResponse.EventResponse.displayName = 'proto.protos.SubsrcribeResponse.EventResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.protos.SubsrcribeResponse.UploadResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.protos.SubsrcribeResponse.UploadResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.protos.SubsrcribeResponse.UploadResponse.displayName = 'proto.protos.SubsrcribeResponse.UploadResponse';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.protos.SubsrcribeResponse.oneofGroups_ = [[9,10]];

/**
 * @enum {number}
 */
proto.protos.SubsrcribeResponse.MessageDataCase = {
  MESSAGE_DATA_NOT_SET: 0,
  UPLOAD_STATUS: 9,
  EVENT_INFO: 10
};

/**
 * @return {proto.protos.SubsrcribeResponse.MessageDataCase}
 */
proto.protos.SubsrcribeResponse.prototype.getMessageDataCase = function() {
  return /** @type {proto.protos.SubsrcribeResponse.MessageDataCase} */(jspb.Message.computeOneofCase(this, proto.protos.SubsrcribeResponse.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.protos.SubsrcribeResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.protos.SubsrcribeResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.protos.SubsrcribeResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.protos.SubsrcribeResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 8, 0),
    uploadStatus: (f = msg.getUploadStatus()) && proto.protos.SubsrcribeResponse.UploadResponse.toObject(includeInstance, f),
    eventInfo: (f = msg.getEventInfo()) && proto.protos.SubsrcribeResponse.EventResponse.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.protos.SubsrcribeResponse}
 */
proto.protos.SubsrcribeResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.protos.SubsrcribeResponse;
  return proto.protos.SubsrcribeResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.protos.SubsrcribeResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.protos.SubsrcribeResponse}
 */
proto.protos.SubsrcribeResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 8:
      var value = /** @type {!proto.protos.SubsrcribeResponse.MessageType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 9:
      var value = new proto.protos.SubsrcribeResponse.UploadResponse;
      reader.readMessage(value,proto.protos.SubsrcribeResponse.UploadResponse.deserializeBinaryFromReader);
      msg.setUploadStatus(value);
      break;
    case 10:
      var value = new proto.protos.SubsrcribeResponse.EventResponse;
      reader.readMessage(value,proto.protos.SubsrcribeResponse.EventResponse.deserializeBinaryFromReader);
      msg.setEventInfo(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.protos.SubsrcribeResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.protos.SubsrcribeResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.protos.SubsrcribeResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.protos.SubsrcribeResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      8,
      f
    );
  }
  f = message.getUploadStatus();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      proto.protos.SubsrcribeResponse.UploadResponse.serializeBinaryToWriter
    );
  }
  f = message.getEventInfo();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      proto.protos.SubsrcribeResponse.EventResponse.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.protos.SubsrcribeResponse.MessageType = {
  EVENT: 0,
  UPLOAD_STATUS: 1,
  UPLOAD_CANCEL: 2
};




if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.protos.SubsrcribeResponse.EventResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.protos.SubsrcribeResponse.EventResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.protos.SubsrcribeResponse.EventResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.protos.SubsrcribeResponse.EventResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    details: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.protos.SubsrcribeResponse.EventResponse}
 */
proto.protos.SubsrcribeResponse.EventResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.protos.SubsrcribeResponse.EventResponse;
  return proto.protos.SubsrcribeResponse.EventResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.protos.SubsrcribeResponse.EventResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.protos.SubsrcribeResponse.EventResponse}
 */
proto.protos.SubsrcribeResponse.EventResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setDetails(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.protos.SubsrcribeResponse.EventResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.protos.SubsrcribeResponse.EventResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.protos.SubsrcribeResponse.EventResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.protos.SubsrcribeResponse.EventResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDetails();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string details = 1;
 * @return {string}
 */
proto.protos.SubsrcribeResponse.EventResponse.prototype.getDetails = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.protos.SubsrcribeResponse.EventResponse} returns this
 */
proto.protos.SubsrcribeResponse.EventResponse.prototype.setDetails = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.protos.SubsrcribeResponse.UploadResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.protos.SubsrcribeResponse.UploadResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.protos.SubsrcribeResponse.UploadResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.protos.SubsrcribeResponse.UploadResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    fileId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    total: jspb.Message.getFieldWithDefault(msg, 2, 0),
    current: jspb.Message.getFieldWithDefault(msg, 3, 0),
    workerId: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.protos.SubsrcribeResponse.UploadResponse}
 */
proto.protos.SubsrcribeResponse.UploadResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.protos.SubsrcribeResponse.UploadResponse;
  return proto.protos.SubsrcribeResponse.UploadResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.protos.SubsrcribeResponse.UploadResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.protos.SubsrcribeResponse.UploadResponse}
 */
proto.protos.SubsrcribeResponse.UploadResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setFileId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTotal(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCurrent(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setWorkerId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.protos.SubsrcribeResponse.UploadResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.protos.SubsrcribeResponse.UploadResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.protos.SubsrcribeResponse.UploadResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.protos.SubsrcribeResponse.UploadResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFileId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTotal();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getCurrent();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getWorkerId();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
};


/**
 * optional string file_id = 1;
 * @return {string}
 */
proto.protos.SubsrcribeResponse.UploadResponse.prototype.getFileId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.protos.SubsrcribeResponse.UploadResponse} returns this
 */
proto.protos.SubsrcribeResponse.UploadResponse.prototype.setFileId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int64 total = 2;
 * @return {number}
 */
proto.protos.SubsrcribeResponse.UploadResponse.prototype.getTotal = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.protos.SubsrcribeResponse.UploadResponse} returns this
 */
proto.protos.SubsrcribeResponse.UploadResponse.prototype.setTotal = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int64 current = 3;
 * @return {number}
 */
proto.protos.SubsrcribeResponse.UploadResponse.prototype.getCurrent = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.protos.SubsrcribeResponse.UploadResponse} returns this
 */
proto.protos.SubsrcribeResponse.UploadResponse.prototype.setCurrent = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 worker_id = 4;
 * @return {number}
 */
proto.protos.SubsrcribeResponse.UploadResponse.prototype.getWorkerId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.protos.SubsrcribeResponse.UploadResponse} returns this
 */
proto.protos.SubsrcribeResponse.UploadResponse.prototype.setWorkerId = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional MessageType type = 8;
 * @return {!proto.protos.SubsrcribeResponse.MessageType}
 */
proto.protos.SubsrcribeResponse.prototype.getType = function() {
  return /** @type {!proto.protos.SubsrcribeResponse.MessageType} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {!proto.protos.SubsrcribeResponse.MessageType} value
 * @return {!proto.protos.SubsrcribeResponse} returns this
 */
proto.protos.SubsrcribeResponse.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 8, value);
};


/**
 * optional UploadResponse upload_status = 9;
 * @return {?proto.protos.SubsrcribeResponse.UploadResponse}
 */
proto.protos.SubsrcribeResponse.prototype.getUploadStatus = function() {
  return /** @type{?proto.protos.SubsrcribeResponse.UploadResponse} */ (
    jspb.Message.getWrapperField(this, proto.protos.SubsrcribeResponse.UploadResponse, 9));
};


/**
 * @param {?proto.protos.SubsrcribeResponse.UploadResponse|undefined} value
 * @return {!proto.protos.SubsrcribeResponse} returns this
*/
proto.protos.SubsrcribeResponse.prototype.setUploadStatus = function(value) {
  return jspb.Message.setOneofWrapperField(this, 9, proto.protos.SubsrcribeResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.protos.SubsrcribeResponse} returns this
 */
proto.protos.SubsrcribeResponse.prototype.clearUploadStatus = function() {
  return this.setUploadStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.protos.SubsrcribeResponse.prototype.hasUploadStatus = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional EventResponse event_info = 10;
 * @return {?proto.protos.SubsrcribeResponse.EventResponse}
 */
proto.protos.SubsrcribeResponse.prototype.getEventInfo = function() {
  return /** @type{?proto.protos.SubsrcribeResponse.EventResponse} */ (
    jspb.Message.getWrapperField(this, proto.protos.SubsrcribeResponse.EventResponse, 10));
};


/**
 * @param {?proto.protos.SubsrcribeResponse.EventResponse|undefined} value
 * @return {!proto.protos.SubsrcribeResponse} returns this
*/
proto.protos.SubsrcribeResponse.prototype.setEventInfo = function(value) {
  return jspb.Message.setOneofWrapperField(this, 10, proto.protos.SubsrcribeResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.protos.SubsrcribeResponse} returns this
 */
proto.protos.SubsrcribeResponse.prototype.clearEventInfo = function() {
  return this.setEventInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.protos.SubsrcribeResponse.prototype.hasEventInfo = function() {
  return jspb.Message.getField(this, 10) != null;
};


